name: Simple CI Check

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show Date
        run: date
        
      - name: List Repository Files
        run: ls -la
        
      - name: Success Message
        run: echo "✅ GitHub Actions Workflow Completed Successfully!"
